-- Active: 1720539271019@@127.0.0.1@5432@seadev


DROP TABLE IF EXISTS piecejointe;
DROP TABLE IF EXISTS commentaire;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS raison;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS utilisateur;


CREATE TABLE utilisateur(
    id_utilisateur SERIAL PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL, -- Stockage du mot de passe haché
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE status(
    id_status SERIAL PRIMARY KEY,
    nom_status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE raison(
    id_raison SERIAL PRIMARY KEY,
    nom_raison VARCHAR(50) NOT NULL UNIQUE,
    icone_raison VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ticket(
    id_ticket SERIAL PRIMARY KEY,
    demande_ticket TEXT NOT NULL,
    id_utilisateur INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    id_raison INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_status) REFERENCES status (id_status) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_utilisateur) REFERENCES utilisateur (id_utilisateur) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_raison) REFERENCES raison (id_raison) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE commentaire(
    id_commentaire SERIAL PRIMARY KEY,
    c_contenu TEXT NOT NULL,
    id_ticket INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_ticket) REFERENCES ticket (id_ticket) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE piecejointe(
    id_pj SERIAL PRIMARY KEY,
    adresse_pj VARCHAR(255) NOT NULL,
    id_ticket INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_ticket) REFERENCES ticket (id_ticket) ON UPDATE CASCADE ON DELETE CASCADE
);
